### ISSUE TITLE
Cannot read properties of undefined (reading 'nodeName')

### ISSUE THREAD

**Issue by Gustavopereira42** [alonrbar/easy-template-x#103]
Hi, I'm facing an error when trying to process a file:

```node_modules/easy-template-x/dist/cjs/easy-template-x.js:1937
    if (sectionProps.nodeName != 'w:sectPr') return null;
                     ^

TypeError: Cannot read properties of undefined (reading 'nodeName')
    at Docx.getHeaderOrFooter (/home/leader/workspace/test-template/node_modules/easy-template-x/dist/cjs/easy-template-x.js:1937:22)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async Docx.getContentPart (/home/leader/workspace/test-template/node_modules/easy-template-x/dist/cjs/easy-template-x.js:1904:16)
    at async Promise.all (index 1)
    at async Docx.getContentParts (/home/leader/workspace/test-template/node_modules/easy-template-x/dist/cjs/easy-template-x.js:1913:19)
    at async TemplateHandler.process (/home/leader/workspace/test-template/node_modules/easy-template-x/dist/cjs/easy-template-x.js:3069:26)
    at async file:///home/leader/workspace/test-template/index.js:142:13
```

For more context, it happens just by using a specific file that was generated from Google Docs, and here is the docx file if you want to take a look by yourself:
[example.docx](https://github.com/alonrbar/easy-template-x/files/14213351/example.docx)

I debugged and seems like the xmlRoot does not have `childNodes`, which results in the error above. I locally did some tests and changed the `if` condition in src/office/docx.ts:119 to `(!sectionProps || sectionProps.nodeName != 'w:sectPr')` and seems like everything works fine. I don't know if there is any negative impact if we change that, but I can look further and open a Pull Request soon if you agree.

**Comment by alonrbar** [comment]
Version 3.2.1 with the fix of #112 is in. Tested with `example.docx` and it seems to work.
