### ISSUE TITLE
Multiple conditional tags in a single table cell throws error

### ISSUE THREAD

**Issue by sj-1010** [alonrbar/easy-template-x#110]
When you have multiple conditions in a single table cell it throws a `Node has no parent` error.
Example of what I have in my docx template:

|Test| Test |
| --- | --- |
| {#hello}HELLO{/}{#bye}BYE{/} | Test |

Template: [test.docx](https://github.com/alonrbar/easy-template-x/files/15287732/test.docx)

Call stack:
```
Error: Node has no parent
    at Object.remove (easy-template-x.js:646:33)
    at LoopTableStrategy.mergeBack (easy-template-x.js:2520:13)
    at LoopPlugin.containerTagReplacements (easy-template-x.js:2578:18)
    at async TemplateCompiler.doTagReplacements (easy-template-x.js:2777:11)
    at async TemplateCompiler.compile (easy-template-x.js:2745:5)
    at async TemplateHandler.process (easy-template-x.js:3043:7)
```

**Comment by alonrbar** [comment]
Fixed in v4.0.0
