### ISSUE TITLE
Corrupted file when writeFileSync and encounter weird behavior

### ISSUE THREAD

**Issue by thanhmd** [alonrbar/easy-template-x#62]
I have the following code to test and parse the file test.docx. But seem weird that the file is corrupted when we have the content inside beginning with the word **certificate**, and if I remove the leading **certificate** word inside the docx file. The convert is success. Can anybody explain?

```
const { TemplateHandler } = require("easy-template-x");
const fs = require("fs");
const unoconv = require('awesome-unoconv');


const parseDoc = async () => {
    const handler = new TemplateHandler();
    try {
        const templateFile = fs.readFileSync('test.docx');

        const data = {
            name: 'test',
            unit_number: '1111',
        };
        const updatedDoc = await handler.process(templateFile, data);
        fs.writeFileSync('test.docx', updatedDoc); // success convert but when write the file it become corrupted
        await unoconv.convert('test.docx', 'test.pdf');
    } catch (error) {
        // thow error here
        console.log(error)
    }

}

parseDoc();

```
Error:
```Error: unoconv: UnoException during import phase:
The document 'file:///var/www/sparebox-admin/test.docx' could not be opened.

    at ChildProcess.<anonymous> (/var/www/sparebox-admin/node_modules/awesome-unoconv/dist/converter.js:147:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
 ```

[test.docx](https://github.com/alonrbar/easy-template-x/files/8085404/test.docx): this file would cause an error with the word "**certificate**" leading

[test.docx](https://github.com/alonrbar/easy-template-x/files/8085414/test.docx): this file is successful without the word "**certificate**" leading

Version:
`"easy-template-x": "^1.0.1"` and `"easy-template-x": "^2.1.0"`
`"awesome-unoconv": "^1.0.1"`

**Comment by alonrbar** [comment]
The issue happens due to error in processing an attribute that have a `&quot;` in it:

```
<w:bookmarkStart w:id="0" w:name="Attachment:_&quot;SB_00_01_09_20.pdf&quot;"/>
<w:bookmarkStart w:id="1" w:name="Attachment:_&quot;SB_00_03_09_20.pdf&quot;"/>
<w:bookmarkStart w:id="2" w:name="Attachment:_&quot;SB_00_04_09_20.pdf&quot;"/>
<w:bookmarkStart w:id="3" w:name="Attachment:_&quot;SB_00_05_09_20.pdf&quot;"/>
```

This is wrongly converted into this: 
```
<w:bookmarkStart w:id="0" w:name="Attachment:_" SB_00_01_09_20.pdf""/>
<w:bookmarkStart w:id="1" w:name="Attachment:_" SB_00_03_09_20.pdf""/>
<w:bookmarkStart w:id="2" w:name="Attachment:_" SB_00_04_09_20.pdf""/>
<w:bookmarkStart w:id="3" w:name="Attachment:_" SB_00_05_09_20.pdf""/>
```
